CREATE TABLE BANCO 
    ( 
     codigo_banco NUMBER(2) NOT NULL, 
     nombre VARCHAR2(25) NOT NULL, 
     CONSTRAINT BANCO_PK PRIMARY KEY (codigo_banco)
    );

CREATE TABLE BOLETA 
    ( 
     codigo_boleta NUMBER(5) NOT NULL, 
     monto_total NUMBER(5) NOT NULL, 
     metodo_pago VARCHAR2(25) NOT NULL, 
     fecha DATE NOT NULL, 
     BANCO_codigo_banco NUMBER(2) NOT NULL, 
     CONSTRAINT BOLETA_PK PRIMARY KEY (codigo_boleta), 
     CONSTRAINT CHK_METODO_PAGO CHECK (metodo_pago IN ('efectivo', 'tarjeta', 'transferencia'))
    );

CREATE TABLE CIUDAD 
    ( 
     id_ciudad NUMBER(5) NOT NULL, 
     nombre VARCHAR2(25) NOT NULL, 
     REGION_id_region NUMBER(5) NOT NULL, 
     CONSTRAINT CIUDAD_PK PRIMARY KEY (id_ciudad)
    );

CREATE TABLE COMUNA 
    ( 
     id_comuna NUMBER(5) GENERATED ALWAYS AS IDENTITY 
        START WITH 1101 
        INCREMENT BY 1 PRIMARY KEY, 
     nombre VARCHAR2(25) NOT NULL, 
     CIUDAD_id_ciudad NUMBER(5) NOT NULL
    );

CREATE TABLE DIAGNOSTICO 
    ( 
     codigo_diagnostico NUMBER(3) NOT NULL, 
     nombre VARCHAR2(25), 
     CONSTRAINT DIAGNOSTICO_PK PRIMARY KEY (codigo_diagnostico)
    );

CREATE TABLE DIGITADOR 
    ( 
     id_digitador NUMBER(4) NOT NULL, 
     p_nombre VARCHAR2(25) NOT NULL, 
     s_nombre VARCHAR2(25), 
     p_apellido VARCHAR2(25) NOT NULL, 
     s_apellido VARCHAR2(25), 
     CONSTRAINT DIGITADOR_PK PRIMARY KEY (id_digitador)
    );

CREATE TABLE DOSIS 
    ( 
     medicamento_cod NUMBER(7) NOT NULL, 
     receta_codigo NUMBER(7) NOT NULL, 
     unidades_medicamento NUMBER(2) NOT NULL, 
     dosis VARCHAR2(25) NOT NULL, 
     dias_tratamiento NUMBER(2) NOT NULL, 
     MEDICAMENTO_codigo_med NUMBER(7) NOT NULL, 
     RECETA_codigo_receta NUMBER(7) NOT NULL, 
     CONSTRAINT DOSIS_PK PRIMARY KEY (medicamento_cod, receta_codigo)
    );

CREATE TABLE ESPECIALIDAD 
    ( 
     codigo_esp NUMBER(3) GENERATED ALWAYS AS IDENTITY 
        START WITH 1 
        INCREMENT BY 1 PRIMARY KEY, 
     nombre VARCHAR2(25) NOT NULL
    );

CREATE TABLE MEDICAMENTO 
    ( 
     codigo_med NUMBER(7) NOT NULL, 
     nombre VARCHAR2(25) NOT NULL, 
     TIPO_MED_cod_tipo_med NUMBER(3) NOT NULL, 
     VIAS_ADM_cod_vias_ad NUMBER(3) NOT NULL, 
     valor_unitario NUMBER(7) NOT NULL, 
     CONSTRAINT MEDICAMENTO_PK PRIMARY KEY (codigo_med)
    );

CREATE TABLE MEDICO 
    ( 
     id_medico NUMBER(5) NOT NULL, 
     p_nombre VARCHAR2(25) NOT NULL, 
     s_nombre VARCHAR2(25), 
     p_apellido VARCHAR2(25) NOT NULL, 
     s_apellido VARCHAR2(25) NOT NULL, 
     telefono VARCHAR2(11) NOT NULL, 
     ESPECIALIDAD_cod_esp NUMBER(3) NOT NULL, 
     CONSTRAINT MEDICO_PK PRIMARY KEY (id_medico), 
     CONSTRAINT MEDICO_telefono_UN UNIQUE (telefono)
    );

CREATE TABLE PACIENTE 
    ( 
     rut NUMBER(8) NOT NULL, 
     dv CHAR(1) NOT NULL, 
     p_nombre VARCHAR2(25) NOT NULL, 
     s_nombre VARCHAR2(25), 
     p_apellido VARCHAR2(25) NOT NULL, 
     s_apellido VARCHAR2(25) NOT NULL, 
     telefono NUMBER(11) NOT NULL, 
     calle VARCHAR2(25) NOT NULL, 
     numeracion NUMBER(5) NOT NULL, 
     COMUNA_id_comuna NUMBER NOT NULL, 
     CONSTRAINT PACIENTE_PK PRIMARY KEY (rut)
    );

CREATE TABLE RECETA 
    ( 
     codigo_receta NUMBER(7) NOT NULL, 
     observaciones VARCHAR2(500), 
     DIGITADOR_id_digitador NUMBER(4) NOT NULL, 
     TIPO_RECETA_codigo_tipo_receta NUMBER(3) NOT NULL, 
     DIAGNOSTICO_codigo_diagnostico NUMBER(3) NOT NULL, 
     MEDICO_id_medico NUMBER(5) NOT NULL, 
     BOLETA_codigo_boleta NUMBER(5) NOT NULL, 
     PACIENTE_rut NUMBER(8) NOT NULL, 
     CONSTRAINT RECETA_PK PRIMARY KEY (codigo_receta)
    );

CREATE TABLE REGION 
    ( 
     id_region NUMBER(5) NOT NULL, 
     nombre VARCHAR2(25) NOT NULL, 
     CONSTRAINT REGION_PK PRIMARY KEY (id_region)
    );

CREATE TABLE TIPO_MED 
    ( 
     codigo_tipo_med NUMBER(3) NOT NULL, 
     descripcion VARCHAR2(25) NOT NULL, 
     CONSTRAINT TIPO_MED_PK PRIMARY KEY (codigo_tipo_med)
    );

CREATE TABLE TIPO_RECETA 
    ( 
     codigo_tipo_receta NUMBER(3) NOT NULL, 
     descripcion VARCHAR2(25) NOT NULL, 
     CONSTRAINT TIPO_RECETA_PK PRIMARY KEY (codigo_tipo_receta)
    );

CREATE TABLE VIAS_ADM 
    ( 
     cod_v_adm NUMBER(3) NOT NULL, 
     descripcion VARCHAR2(25) NOT NULL, 
     CONSTRAINT VIAS_ADMINISTRACION_PK PRIMARY KEY (cod_v_adm)
    );

-- RELACIONES (FOREIGN KEYS)
ALTER TABLE BOLETA ADD CONSTRAINT BOLETA_BANCO_FK FOREIGN KEY (BANCO_codigo_banco) REFERENCES BANCO (codigo_banco);
ALTER TABLE CIUDAD ADD CONSTRAINT CIUDAD_REGION_FK FOREIGN KEY (REGION_id_region) REFERENCES REGION (id_region);
ALTER TABLE COMUNA ADD CONSTRAINT COMUNA_CIUDAD_FK FOREIGN KEY (CIUDAD_id_ciudad) REFERENCES CIUDAD (id_ciudad);
ALTER TABLE DOSIS ADD CONSTRAINT DOSIS_MEDICAMENTO_FK FOREIGN KEY (MEDICAMENTO_codigo_med) REFERENCES MEDICAMENTO (codigo_med);
ALTER TABLE DOSIS ADD CONSTRAINT DOSIS_RECETA_FK FOREIGN KEY (RECETA_codigo_receta) REFERENCES RECETA (codigo_receta);
ALTER TABLE MEDICAMENTO ADD CONSTRAINT MEDI_TIPO_MED_FK FOREIGN KEY (TIPO_MED_cod_tipo_med) REFERENCES TIPO_MED (codigo_tipo_med);
ALTER TABLE MEDICAMENTO ADD CONSTRAINT MED_VIAS_ADM_FK FOREIGN KEY (VIAS_ADM_cod_vias_ad) REFERENCES VIAS_ADM (cod_v_adm);
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_ESPECIALIDAD_FK FOREIGN KEY (ESPECIALIDAD_cod_esp) REFERENCES ESPECIALIDAD (codigo_esp);
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_COMUNA_FK FOREIGN KEY (COMUNA_id_comuna) REFERENCES COMUNA (id_comuna);
ALTER TABLE RECETA ADD CONSTRAINT RECETA_BOLETA_FK FOREIGN KEY (BOLETA_codigo_boleta) REFERENCES BOLETA (codigo_boleta);
ALTER TABLE RECETA ADD CONSTRAINT RECETA_DIAGNOSTICO_FK FOREIGN KEY (DIAGNOSTICO_codigo_diagnostico) REFERENCES DIAGNOSTICO (codigo_diagnostico);
ALTER TABLE RECETA ADD CONSTRAINT RECETA_DIGITADOR_FK FOREIGN KEY (DIGITADOR_id_digitador) REFERENCES DIGITADOR (id_digitador);
ALTER TABLE RECETA ADD CONSTRAINT RECETA_MEDICO_FK FOREIGN KEY (MEDICO_id_medico) REFERENCES MEDICO (id_medico);
ALTER TABLE RECETA ADD CONSTRAINT RECETA_PACIENTE_FK FOREIGN KEY (PACIENTE_rut) REFERENCES PACIENTE (rut);
ALTER TABLE RECETA ADD CONSTRAINT RECETA_TIPO_RECETA_FK FOREIGN KEY (TIPO_RECETA_codigo_tipo_receta) REFERENCES TIPO_RECETA (codigo_tipo_receta);

SELECT * FROM RECETA;